# VisionPilot ROS2 configuration template

source.input_camera_topic   = /sensing/camera/image_raw

vehicle_speed_topic         = /vehicle/speed
vehicle_steering_topic      = /vehicle/steering_cmd
vehicle_acceleration_topic  = /vehicle/throttle_cmd
